name: Build Natives

on:
  push:
    branches:
      - SDL3

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    name: Build Linux Natives

    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        include: [
          # Running on x86_64 runner, nothing extra needed
          { name: "linux-x86_64", packages: "", cmakeargs: "" },
          # Running on aarch64 runner, need to install gcc-aarch64-linux-gnu toolchain
          { name: "linux-aarch64", packages: "gcc-aarch64-linux-gnu", cmakeargs: "-DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++" },
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: BrycensRanch/read-properties-action@v1
        id: read-properties
        with:
          file: gradle.properties
          property: sdlCommit
      - name: Clone SDL3
        run: |
          git clone https://github.com/libsdl-org/SDL.git --branch main --single-branch SDL
          cd SDL
          git reset --hard ${{ steps.read-properties.outputs.sdlCommit }}
      - name: Get build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libpipewire-0.2-dev libwayland-dev libdecor-0-dev liburing-dev ${{ matrix.packages }}
      - name: Build SDL3 for linux64
        working-directory: SDL
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release ${{ matrix.cmakeargs }}
          cmake --build build --config Release
      - name: Add SDL3.so to folder
        run: |
          mkdir -p libs/natives/${{ matrix.name }}
          cp SDL/build/libSDL3.so libs/natives/${{ matrix.name }}/SDL3.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: natives-${{ matrix.name }}
          path: libs/natives/**
